### ISSUE TITLE
Circular heatmap

### ISSUE THREAD

**Issue by eric2302** [LeonDLotter/ABAnnotate#5]
Hey @LeonDLotter,

I really like the visualization you use in your [example notebook](https://github.com/LeonDLotter/ABAnnotate/blob/main/example/example_pain.ipynb) (see below)
![image](https://github.com/LeonDLotter/ABAnnotate/assets/52158179/e2acb57b-abaa-430b-95da-4cc035772c68)

Can you share where you got the function from?

Best regards,
Eric

**Comment by LeonDLotter** [comment]
Hi @eric2302,

of course: it is the `heatmap` function from the [heatmapz](https://pypi.org/project/heatmapz/) package, which confusingly is imported via `from heatmap import heatmap`. 

However, in hindsight, it is easier to just create such heatmaps from scratch using matplotlib and seaborn. Here would be an example that I quickly made:

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# EXAMPLE DATA
# columns and rows
cols = [f"Col {i}" for i in range(1, 11)]
rows = [f"Row {i}" for i in range(1, 6)]
# background "effect sizes", random samples in interval (-0.2,0.2)
df_effectsizes = pd.DataFrame(np.random.uniform(-0.4,0.4, (len(rows),len(cols))), columns=cols, index=rows)
# background "p values", random samples in interval (0.2,1)
df_pvalues = pd.DataFrame(np.random.uniform(0.2,1, (len(rows),len(cols))), columns=cols, index=rows)
# add negative effects in upper left and lower right corner 
df_effectsizes.loc["Row 1", "Col 1"], df_pvalues.loc["Row 1", "Col 1"] = -1, 0.001
df_effectsizes.loc["Row 5", "Col 10"], df_pvalues.loc["Row 5", "Col 10"] = -1, 0.001
# add positive effects in complete second row 
df_effectsizes.loc[rows[1], :], df_pvalues.loc[rows[1], :] = 1, 0.001

# PLOT
fig, ax = plt.subplots(1, figsize=(8,3))
fig.set_facecolor("w")
ax.set_aspect("equal")
# indices to cover the complete tables
x_indices, y_indices = np.meshgrid(range(len(cols)), range(len(rows)))
# make scatterplot from a combined dataframe
sns.scatterplot(
    data=pd.DataFrame({
        "Columns": [cols[i] for i in x_indices.flatten()],
        "Rows": [rows[i] for i in y_indices.flatten()],
        "Sizes": 1 - df_pvalues.values.flatten("C"),
        "Colors": df_effectsizes.values.flatten("C"),
    }),
    x="Columns",
    y="Rows",
    size="Sizes",
    sizes=(10,600),
    hue="Colors",
    palette="icefire",
    legend=None
)
# padding at the outside of x and y axes
axes_pad = 0.5
ax.set_xlim(-axes_pad, len(cols)-axes_pad)
ax.set_ylim(len(rows)-axes_pad, -axes_pad)

fig.savefig("scatter_heatmap.png", bbox_inches="tight", dpi=300)
```
This produces the following plot:
![scatter_heatmap](https://github.com/LeonDLotter/ABAnnotate/assets/84286176/32853589-4cc5-47f2-bb72-217a386ecdfa)

You can also easily add another categorical visual dimension with the `style` attribute of [`seaborn.scatterplot`](https://seaborn.pydata.org/generated/seaborn.scatterplot.html).

Hope that helps!

Best wishes,
Leon

**Comment by eric2302** [comment]
Amazing! Thank you for the example :)

I'm going to close the issue then
